C-----AFIX.FOR
C     THIS ROUTINE PROVIDES THE BRACKET FUNCTION.  IT MAY
C     BE USED WHEN THE RESULT IS OUT OF THE INTEGER RANGE
C     OF THE MACHINE BEING USED.  OTHERWISE IT WOULD BE
C     EQUIVALENT TO FLOAT(JFIX(X)).  JFIX COULD BE IFIX
C     EXCEPT THAT MOST FORTRAN IMPLEMENTATIONS DO NOT
C     PROPERLY CALCULATE THE BRACKET FUNCTION, BUT RATHER
C     MAKE IFIX EQUIVALENT TO INT.  SEE JFIX.
C-----
      FUNCTION AFIX(X)
C      
      IMPLICIT NONE
C      
      REAL*4 X, AFIX, AINT
C      
      AFIX=AINT(X)
      IF (AFIX.EQ.X) RETURN
      IF (X.LT.0.0) AFIX=AFIX-1.0
      RETURN
      END
