      INTEGER FUNCTION GW(Q)
      IMPLICIT INTEGER(A-Z)
      PARAMETER ( JBLK=126 )
      DIMENSION BUF(JBLK)
      DATA BUFPT/ 32000 /
      IF (BUFPT.LE.JBLK) GO TO 1
      READ(2) BUF
      BUFPT=1
    1 GW=BUF(BUFPT)
      BUFPT=BUFPT+1
      RETURN
      END
