C-----NXTW.FOR
      FUNCTION NXTW(K)
      PARAMETER ( JBLK=126 )
      DIMENSION JBUF(JBLK)
      COMMON /IOUNIT/LU1,LU2,LU3,LU4,LU5
      IF (K.GE.0) GO TO 1
      REWIND LU4
      INDEX=JBLK
      NXTW=0
      RETURN
    1 INDEX=INDEX+1
      IF (INDEX.LE.JBLK) GO TO 2
      READ (LU4) JBUF
      INDEX=1
    2 NXTW=JBUF(INDEX)
      RETURN
      END
