C-----PLOTS.FOR
C
C      THIS IS THE INITIALIZATION SUBROUTINE.  THE ARGUMENTS
C      ARE IGNORED, AND ARE PRESENT ONLY FOR COMPATIBILITY.
C
      SUBROUTINE PLOTS(I1,I2,I3)
      COMMON /PLTCOM/
     &SAME,PREF(2),LDC(2),C(2),RORG(2),CMAT(10,3),LMT(2),
     &XYDOTS(2),SPX,SPY,MIX,NSKP,NBAD,
     &NPLOT,MINX,MAXX,NDX,NDY,LTYPE,LWDTH,DEGRAD,
     &NBITS,NBTM1,NBYTE,NBYM1,NCHAR,NCHM1,MSK(7),IBT(16)
      DO 10 I=1,2
      RORG(I)=0.0
      J=I+1
      CMAT(J,1)=FLOAT(LMT(I))/XYDOTS(I)
      CMAT(J,2)=0.0
   10 CMAT(J,3)=0.0
      RETURN
      END
