C-----PUTW.FOR
      SUBROUTINE PUTW(K,IW)
      PARAMETER ( JBLK=126 )
      DIMENSION JBUF(JBLK)
      COMMON /IOUNIT/LU1,LU2,LU3,LU4,LU5
      IF (K) 1,2,4
    1 REWIND LU5
      INDEX=0
      RETURN
    2 IF (INDEX.LT.JBLK) GO TO 3
      WRITE (LU5) JBUF
      INDEX=0
    3 INDEX=INDEX+1
      JBUF(INDEX)=IW
      RETURN
    4 WRITE (LU5) JBUF
      INDEX=0
      ENDFILE LU5
      RETURN
      END
