C - SEMILG.FOR
C
C       PROGRAM:        SEMILG.FOR
C       PURPOSE:        TO PLOT SEMILOG GRAPHS
C       AUTHOR:         JIM SIMPSON
C       DATE:           JAN 1981
C       VERSION:        V1.5
C       SYSTEM:         RSTS/E 7.0
C
        SUBROUTINE SEMILG(NUMPTS,X,Y,XTITLE,NXLEN,YTITLE,NYLEN)
        DIMENSION X(NUMPTS),Y(NUMPTS),XTEMP(100),XTITLE(10)
        DIMENSION YTITLE(10),TY(2),TX(2)
        DATA TY/0.0,-0.07/
        DIST=10.
        SAME=9999.0
        FIRST=AFIX(X(1))
        IF (AFIX(X(NUMPTS)).EQ.X(NUMPTS)) GOTO 10
        LAST=AFIX(X(NUMPTS)+1.)
        GOTO 20
10      LAST=AFIX(X(NUMPTS))
20      SCALE=DIST/(LAST-FIRST)
        DO 30 J=1,NUMPTS
30      XTEMP(J)=(X(J)-FIRST)*SCALE
        CALL MODE(2,11.0,SAME,SAME)
        CALL MODE(7,DIST,8.0,SAME)
        CALL SCAN(XTEMP,Y,-NUMPTS,40)
        CALL DRAW(XTEMP,Y,NUMPTS,42)
        CALL AXES(-1.,0,NYLEN+.1,YTITLE)
        CALL MODE(5,SAME,SAME,441.)
        DO 40 J=FIRST,LAST-1
        DO 40 K=1,10
        TEMP=(J-FIRST+ALOG10(FLOAT(K)))*SCALE
40      CALL FORM(1001,TEMP,8,1.0)
        CALL MODE(5,SAME,SAME,440.)
        CALL MODE(4,.15,.10,SAME)
        TEMP=5.-.075*NXLEN
        CALL NOTE(TEMP,-.45,XTITLE,NXLEN)
        CALL MODE(4,.1,.067,SAME)
        DO 50 J=FIRST,LAST
        TEMP=(J-FIRST)*SCALE
        TX(1)=TEMP
        TX(2)=TEMP
        CALL DRAW(TX,TY,2,1)
50      CALL NOTE(TEMP,-.25,J,0)
        RETURN
        END
