
     1
     1You are standing at the end of a road before a small brick building.
     1around you is a forest.  A small stream flows out of the building and
     1down a gully.
     2You have walked up a hill, still in the forest.  The road slopes back
     2down the other side of the hill.  There is a building in the distance.
     3You are inside a building, a well house for a large spring.
     4You are in a valley in the forest beside a stream tumbling along a
     4rocky bed.
     5You are in open forest, with a deep valley to one side.
     6You are in open forest near both a valley and a road.
     7At your feet all the water of the stream splashes into a 2-inch slit
     7in the rock.  Downstream the streambed is bare rock.
     8You are in a 20-foot depression floored with bare dirt.  Set into the
     8dirt is a strong steel grate mounted in concrete.  A dry streambed
     8leads into the depression.
     9You are in a small chamber beneath a 3x3 steel grate to the surface.
     9A low crawl over cobbles leads inward to the west.
    10You are crawling over cobbles in a low passage.  There is a dim light
    10at the east end of the passage.
    11You are in a debris room filled with stuff washed in from the surface.
    11A low wide passage with cobbles becomes plugged with mud and debris
    11here, but an awkward canyon leads upward and west.  A note on the wall
    11says "Magic Word XYZZY".
    12You are in an awkward sloping east/west canyon.
    13You are in a splendid chamber thirty feet high.  The walls are frozen
    13rivers of orange stone.  An awkward canyon and a good passage exit
    13from east and west sides of the chamber.
    14At your feet is a small pit breathing traces of white mist.  An east
    14passage ends here except for a small crack leading on.
    15You are at one end of a vast hall stretching forward out of sight to
    15the west.  There are openings to either side.  Nearby, a wide stone
    15staircase leads downward.  The hall is filled with wisps of white mist
    15swaying to and fro almost as if alive.  A cold wind blows up the
    15staircase.  There is a passage at the top of a dome behind you.
    16The crack is far too small for you to follow.  Your only alternative
    16is to back out.
    17You are on the east bank of a fissure slicing clear across the hall.
    17The mist is quite thick here, and the fissure is too wide to jump.
    18This is a low room with a crude note on the wall.  The note says,
    18"You won't get it up the steps".
    19You are in the Hall of the Mountain King, with passages off in all
    19directions.
    20You are at the bottom of the pit with a broken neck.
    21You didn't make it.
    22You are in a forest of bioluminescent toad stools.
    23You are at the West end of the twopit room.  There is a large hole in
    23the wall above the pit at this end of the room.
    24You are at the bottom of the Eastern pit in the twopit room.  There is
    24a small pool of oil in one corner of the pit.
    25You are at the bottom of the western pit in the twopit room.  There is
    25a large hole in the wall about 25 feet above you.
    26You have clambered up the plant and scurred through the hole at
    26the top.  You are on the lip of a large hole above the west pit.
    27You are on the West side of the fissure in the hall of mists.
    28You are in a low N/S passage at a hole in the floor.  The hole goes
    28down to an E/W passage.
    29You are in the South side chamber.
    30You are in the West side chamber of the Hall of the Mountain King.
    30A passage continues west and up here.
    31>$<
    32You can't get by the snake.
    33You are in a large room, with a passage to the South, a passage to the
    33West, and a wall of broken rock to the East.  There is a large "Y2" on
    33a rock in the room's center.
    34You are in a jumble of rock, with cracks everywhere.
    35You're at a low window overlooking a huge pit, which extends up out of
    35sight.  A floor is indistinctly visible over 50 feet below.  Traces of
    35white mist cover the floor of the pit, becoming thicker to the right.
    35Marks in the dust around the window would seem to indicate that
    35someone has been here recently.  Directly across the pit from you and
    3525 feet away there is a similar window looking into a lighted room.  A
    35shadowy figure can be seen there peering back at you.
    36You are in a dirty broken passage.  To the East is a crawl.  To the
    36west is a large passage.  Above you is a hole to another passage.
    37You are on the brink of a small clean climbable pit.  A crawl leads
    37West.
    38You are in the bottom of a small pit with a little stream, which
    38enters and exits through tiny slits.
    39You are in a large room full of dusty rocks.  There is a big hole in
    39the floor.  There are cracks everywhere, and a passage leading East.
    40You have crawled through a very low wide passage parallel to and North
    40of the hall of mists.
    41You are at the west end of hall of mists.  A low wide crawl continues
    41West and another goes North.  To the South is a little passage 6 feet
    41off the floor.
    42You are in a maze of twisty little passages, all alike.
    43You are in a maze of twisty little passages, all alike.
    44You are in a maze of twisty little passages, all alike.
    45You are in a maze of twisty little passages, all alike.
    46Dead end
    47Dead end
    48Dead end
    49You are in a maze of twisty little passages, all alike.
    50You are in a maze of twisty little passages, all alike.
    51You are in a maze of twisty little passages, all alike.
    52You are in a maze of twisty little passages, all alike.
    53You are in a maze of twisty little passages, all alike.
    54Dead end
    55You are in a maze of twisty little passages, all alike.
    56Dead end
    57You are on the brink of a thirty foot pit with a massive orange column
    57down one wall.  You could climb down here but you could not get back
    57up.  The maze continues at this level.
    58Dead end
    59You have crawled into a very low wide passage parallel to and north
    59of the hall of mists.
    60You are at the east end of a very long hall apparently without side
    60chambers.  To the east a low wide crawl slants up.  To the north a
    60round two foot hole slants down.
    61You are at the west end of a very long featureless hall.  The hall
    61joins up with a narrow north/south passage.
    62You are at a crossover of a high N/S passage and a low E/W one.
    63Dead end
    64You are at a complex junction.  A low hands and knees passage from the
    64north joins a higher crawl from the east to make a walking passage
    64going west.  There is also a large room above.  The air is damp here.
    65You are in bedquilt, a long east/west passage with holes everywhere.
    65To explore at random select north, south, up, or down.
    66You are in a room whose walls resemble swiss cheese.  Obvious passages
    66go west, east, NE, and NW.  Part of the room is occupied by a large
    66bedrock block.
    67You are at the east end of the twopit room.  The floor here is
    67littered with thin rock slabs, which make it easy to descend the pits.
    67There is a path here bypassing the pits to connect passages from east
    67and west.  There are holes all over, but the only big one is on the
    67wall directly over the west pit where you can't get to it.
    68You are in a large low circular chamber whose floor is an immense slab
    68fallen from the ceiling (Slab room).  East and west there once were
    68large passages, but they are now filled with boulders.  Low small
    68passages go north and south, and the south one quickly bends west
    68around the boulders.
    69You are in a secret N/S canyon above a large room.
    70You are in a secret N/S canyon above a sizable passage.
    71You are in a secret canyon at a junction of three canyons, bearing
    71north, south, and SE.  The north one is as tall as the other two
    71combined.
    72You are in a large low room.  Crawls lead north, SE, and SW.
    73Dead end crawl.
    74You are in a secret canyon which here runs E/W.  It crosses over a
    74very tight canyon 15 feet below.  If you go down you may not be able
    74to get back up.
    75You are at a wide place in a very tight N/S canyon.
    76The canyon here becomes too tight to go further south.
    77You are in a tall E/W canyon.  A low tight crawl goes 3 feet north and
    77seems to open up.
    78The canyon runs into a mass of boulders -- dead end.
    79The stream flows out through a pair of 1 foot diameter sewer pipes.
    79It would be advisable to use the exit.
    80You are in a maze of twisty little passages, all alike.
    81Dead end
    82Dead end
    83You are in a maze of twisty little passages, all alike.
    84You are in a maze of twisty little passages, all alike.
    85Dead end
    86Dead end
    87You are in a maze of twisty little passages, all alike.
    88You are in a long, narrow corridor stretching out of sight to the
    88west.  At the eastern end is a hole through which you can see a
    88profusion of leaves.
    89There is nothing here to climb.  use "UP" or "OUT" to leave the pit.
    90You have climbed up the plant and out of the pit.
    91You are at the top of a steep incline above a large room.  You could
    91climb down here, but you would not be able to climb up.  There is a
    91passage leading back to the north.
    92You are in the giant room.  The ceiling here is too high up for your
    92lamp to show it.  Cavernous passages lead east, north, and south.  On
    92the west wall is scrawled the inscription, "FEE FIE FOE FOO" [sic].
    93The passage here is blocked by a recent cave-in.
    94You are at one end of an immense north/south passage.
    95You are in a magnificent cavern with a rushing stream, which cascades
    95over a sparkling waterfall into a roaring whirlpool which disappears
    95through a hole in the floor.  Passages exit to the south and west.
    96You are in the soft room.  The walls are covered with heavy curtains,
    96the floor with a thick pile carpet.  Moss covers the ceiling.
    97This is the oriental room.  Ancient oriental cave drawings cover the
    97walls.  A gently sloping passage leads upward to the north, another
    97passage leads SE, and a hands and knees crawl leads west.
    98You are following a wide path around the outer edge of a large cavern.
    98Far below, through a heavy white mist, strange splashing noises can be
    98heard.  The mist rises up through a fissure in the ceiling.  The path
    98exits to the south and west.
    99You are in an alcove.  A small nw path seems to widen after a short
    99distance.  An extremely tight tunnel leads east.  It looks like a very
    99tight squeeze.  An eerie light can be seen at the other end.
   100You're in a small chamber lit by an eerie green light.  An extremely
   100narrow tunnel exits to the west.  A dark corridor leads NE.
   101You're in the dark-room.  There is a corridor leading south and a
   101climbable crack leading up into the darkness.  If you can hand jamb.
   102You are in an arched hall.  A coral passage once continued up and east
   102from here, but is now blocked by debris.  The air smells of sea water.
   103You're in a large room carved out of sedimentary rock.  The floor and
   103walls are littered with bits of shells imbedded in the stone.  A
   103shallow passage proceeds downward, and a somewhat steeper one leads
   103up.  A low hands and knees passage enters from the south.
   104You are in a long sloping corridor with ragged sharp walls.
   105You are in a cul-de-sac about eight feet across.
   106You are in an anteroom leading to a large passage to the east.  Small
   106passages go west and up.  The remnants of recent digging are evident.
   106A sign in midair here says "CAVE UNDER CONSTRUCTION BEYOND THIS POINT.
   106PROCEED AT OWN RISK.  [Witt Construction Company]"
   107You are in a maze of twisty little passages, all different.
   108You are at witt's end.  Passages lead off in *ALL* directions.
   109You are in a north/south canyon about 25 feet across.  The floor is
   109covered by white mist seeping in from the north.  The walls extend
   109upward for well over 100 feet.  Suspended from some unseen point far
   109above you, an enormous two-sided mirror is haning parallel to and
   109midway between the canyon walls.  (The mirror is obviously provided
   109for the use of the dwarves, who as you know, are extremely vain.)  A
   109small window can be seen in either wall, some fifty feet up.
   110You're at a low window overlooking a huge pit, which extends up out of
   110sight.  A floor is indistinctly visible over 50 feet below.  Traces of
   110white mist cover the floor of the pit, becoming thicker to the left.
   110Marks in the dust around the window would seem to indicate that
   110someone has been here recently.  Directly across the pit from you and
   11025 feet away there is a similar window looking into a lighted room.  A
   110shadowy figure can be seen there peering back at you.
   111A large stalactite extends from the roof and almost reaches the floor
   111below.  You could climb down it, and jump from it to the floor, but
   111having done so you would be unable to reach it to climb back up.
   112You are in a little maze of twisting passages, all different.
   113You are at the edge of a large underground reservoir.  An opaque cloud
   113of white mist fills the room and rises rapidly upward.  The lake is
   113fed by a stream, which tumbles out of a hole in the wall about 10 feet
   113overhead and splashes noisily into the water somewhere within the
   113mist.  The only passage goes back toward the south.
   114Dead end
   115You are at the northeast end of an immense room, even larger than the
   115giant room.  It appears to be a repository for the "ADVENTURE"
   115program.  Massive torches far overhead bathe the room with smoky
   115yellow light.  Scattered about you can be seen a pile of bottles (All
   115of them empty), a nursery of young beanstalks murmuring quietly, a bed
   115of oysters, a bundle of black rods with rusty stars on their ends, and
   115a collection of brass lanterns.  Off to one side a great many dwarves
   115are sleeping on the floor, snoring loudly.  A sign nearby reads: "DO
   115NOT DISTURB THE DWARVES!"  An immense mirror is hanging against one
   115wall, and stretches to the other end of the room, where various other
   115sundry objects can be glimpsed dimly in the distance.
   116You are at the southwest end of the repository.  To one side is a pit
   116full of fierce green snakes.  On the other side is a row of small
   116wicker cages, each of which contains a little sulking bird.  In one
   116corner is a bundle of black rods with rusty marks on their ends.  A
   116large number of velvet pillows are scattered about on the floor.  A
   116vast mirror stretches off to the northeast.  At your feet is a large
   116steel grate, next to which is a sign which reads, "TREASURE VAULT.
   116KEYS IN MAIN OFFICE."
   117You are on one side of a large, deep chasm.  A heavy white mist rising
   117up from below obscures all view of the far side.  A SW path leads away
   117from the chasm into a winding corridor.
   118You are in a long winding corridor sloping out of sight in both
   118directions.
   119You are in a secret canyon which exits to the north and east.
   120You are in a secret canyon which exits to the north and east.
   121You are in a secret canyon which exits to the north and east.
   122You are on the far side of the chasm.  A NE path leads away from the
   122chasm on this side.
   123You're in a long east/west corridor.  A faint rumbling noise can be
   123heard in the distance.
   124The path forks here.  The left fork leads northeast.  A dull rumbling
   124seems to get louder in that direction.  The right fork leads southeast
   124down a gentle slope.  The main corridor enters from the west.
   125The walls are quite warm here.  From the north can be heard a steady
   125roar, so loud that the entire cave seems to be trembling.  Another
   125passage leads south, and a low crawl goes east.
   126You are on the edge of a breath-taking view.  Far below you is an
   126active volcano, from which great gouts of molten lava come surging
   126out, cascading back down into the depths.  The glowing rock fills the
   126farthest reaches of the cavern with a blood-red glare, giving every-
   126thing an eerie, macabre appearance.  The air is filled with flickering
   126sparks of ash and a heavy smell of brimstone.  The walls are hot to
   126the touch, and the thundering of the volcano drowns out all other
   126sounds.  Embedded in the jagged roof far overhead are myriad twisted
   126formations composed of pure white alabaster, which scatter the murky
   126light into sinister apparitions upon the walls.  To one side is a deep
   126gorge, filled with a bizarre chaos of tortured rock which seems to
   126have been crafted by the devil himself.  An immense river of fire
   126crashes out from the depths of the volcano, burns its way through the
   126gorge, and plummets into a bottomless pit far off to your left.  To
   126the right, an immense geyser of blistering steam erupts continuously
   126from a barren island in the center of a sulfurous lake, which bubbles
   126ominously.  The far right wall is aflame with an incandescence of its
   126own, which lends an additional infernal splendor to the already
   126hellish scene.  A dark, foreboding passage exits to the south.
   127You are in a small chamber filled with large boulders.  The walls are
   127very warm, causing the air in the room to be almost stifling from the
   127heat.  The only exit is a crawl heading west, through which is coming
   127a low rumbling.
   128You are walking along a gently sloping north/south passage lined with
   128oddly shaped limestone formations.
   129You are standing at the entrance to a large, barren room.  A sign
   129posted above the entrance reads:  "CAUTION!  Bear in room!"
   130You are inside a barren room.  The center of the room is completely
   130empty except for some dust.  Marks in the dust lead away toward the
   130far end of the room.  The only exit is the way you came in.
   131You are in a maze of twisting little passages, all different.
   132You are in a little maze of twisty passages, all different.
   133You are in a twisting maze of little passages, all different.
   134You are in a twisting little maze of passages, all different.
   135You are in a twisty little maze of passages, all different.
   136You are in a twisty maze of little passages, all different.
   137You are in a little twisty maze of passages, all different.
   138You are in a maze of little twisting passages, all different.
   139You are in a maze of little twisty passages, all different.
   140Dead end
   141You are on a ledge at the top of a climbable crack.  There is a
   141twisty passage leading off to the north.
   142You are in a magnificent ice cave.  Massive columns of ice extend
   142from ceiling to floor.  The light from your lamp is reflected off
   142the columns in cascading, rainbow like streams of colour that bath
   142the entire cavern with a festive glow.  There is a dark passage
   142to the south and, to the north west, an ancent stairway going up
   142out of sight.  There is also a frozen pathway winding off to the west.
   143You are in a large vaulted hall, standing on top of an ancent
   143ziggurat.  Its heavy walls, articulated by regularly spaced
   143projections and recesses, are sufficently well preserved to
   143suggest something of the original apperance of the structure.
   143The mud brick walls once were covered with a coat of white wash.
   143befor you, to the NE, is an entrance to the cella, or main room,
   143where sacrifices were offered.  A stairway decends to the SE.
   144This is the cella of the ziggurat.  There are many small side
   144passages off this room which runs the length of the temple.
   145You are in a jumble of rocks, with cracks *EVERYWHERE*.
   146You are in a jumble of rocks, with cracks everywhere.  A note on
   146the wall says 'Use fibonacci logic for your next move'.
   147You are in a room with mathematical symbols covering all the
   147walls.  This is fibonacci's secret room.
   148You are at the bottom of a shear ice face.  A frozen passage
   148leads off to the south.
   149You are in a room with many shelves at the top of a shear ice
   149face.  There are many strange symbols drawn on the walls.
   149Obviously this was once the laboratory of an alchemist.
   150You are in a forest of luminescent toad stools.
    -1END
     2
     1You're at end of road again.
     2You're at hill in road.
     3You're inside building.
     4You're in valley.
     5You're in forest.
     6You're in forest.
     7You're at slit in streambed.
     8You're outside grate.
     9You're below the grate.
    10You're in cobble crawl.
    11You're in debris room.
    13You're in bird chamber.
    14You're at top of small pit.
    15You're in hall of mists.
    17You're on east bank of fissure.
    18You're in nugget of gold room.
    19You're in hall of mt king.
    23You're at west end of twopit room.
    24You're in east pit.
    25You're in west pit.
    33You're at "Y2".
    35You're at window on pit.
    36You're in dirty passage.
    39You're in dusty rock room.
    41You're at west end of hall of mists.
    57You're at brink of pit.
    60You're at east end of long hall.
    61You're at west end of long hall.
    64You're at complex junction.
    66You're in swiss cheese room.
    67You're at east end of twopit room.
    68You're in slab room.
    71You're at junction of three secret canyons.
    74You're in secret E/W canyon above tight canyon.
    88You're in narrow corridor.
    91You're at steep incline above large room.
    92You're in giant room.
    95You're in cavern with waterfall.
    96You're in soft room.
    97You're in oriental room.
    98You're in misty cavern.
    99You're in alcove.
   100You're in plover room.
   101You're in dark-room.
   102You're in arched hall.
   103You're in shell room.
   106You're in anteroom.
   108You're at witt's end.
   109You're in mirror canyon.
   110You're at window on pit.
   111You're at top of stalactite.
   113You're at reservoir.
   115You're at NE end.
   116You're at SW end.
   117You're on SW side of chasm.
   118You're in sloping corridor.
   122You're on NE side of chasm.
   123You're in corridor.
   124You're at fork in path.
   125You're at junction with warm walls.
   126You're at breath-taking view.
   127You're in chamber of boulders.
   128You're in limestone passage.
   129You're in front of barren room.
   130You're in barren room.
   142You're in the ice cave.
   143You're at the ziggurat.
   144You're in the cella.
    -1
     3
     1     0     2     2    44    29     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     1     0     3     3    12    19    43     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     1     0     4     5    13    14    46    30     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     1     0     5     6    45    43     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     1     0     8    63     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     2     0     1     2    12     7    43    45    30     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     2     0     5     6    45    46     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     3     0     1     3    11    32    44     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     3     0    11    62     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     3     0    33    65     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     3     0    79     5    14     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     4     0     1     4    12    45     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     4     0     5     6    43    44    29     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     4     0     7     5    46    30     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     4     0     8    63     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     5     0     4     9    43    30     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     5    50     5     6     7    45     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     5     0     6     6     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
     5     0     5    44    46
                       0     0     0     0     0     0     0     0     0     0
     6     0     1     2    45
                       0     0     0     0     0     0     0     0     0     0
     6     0     4     9    43    44    30
                       0     0     0     0     0     0     0     0     0     0
     6     0     5     6    46
                       0     0     0     0     0     0     0     0     0     0
     7     0     1    12
                       0     0     0     0     0     0     0     0     0     0
     7     0     4     4    45
                       0     0     0     0     0     0     0     0     0     0
     7     0     5     6    43    44
                       0     0     0     0     0     0     0     0     0     0
     7     0     8     5    15    16    46
                       0     0     0     0     0     0     0     0     0     0
     7     0   595    60    14    30
                       0     0     0     0     0     0     0     0     0     0
     8     0     5     6    43    44    46
                       0     0     0     0     0     0     0     0     0     0
     8     0     1    12
                       0     0     0     0     0     0     0     0     0     0
     8     0     7     4    13    45
                       0     0     0     0     0     0     0     0     0     0
     8   303   009     3    19    30
                       0     0     0     0     0     0     0     0     0     0
     8     0   593     3
                       0     0     0     0     0     0     0     0     0     0
     9   303   008    11    29
                       0     0     0     0     0     0     0     0     0     0
     9     0   593    11
                       0     0     0     0     0     0     0     0     0     0
     9      10      17      18      19      44
                       0     0     0     0     0     0     0     0     0     0
     9      14      31
                       0     0     0     0     0     0     0     0     0     0
     9      11      51
                       0     0     0     0     0     0     0     0     0     0
    10       9      11      20      21      43
                       0     0     0     0     0     0     0     0     0     0
    10      11      19      22      44      51
                       0     0     0     0     0     0     0     0     0     0
    10      14      31
                       0     0     0     0     0     0     0     0     0     0
    11  303008      63
                       0     0     0     0     0     0     0     0     0     0
    11       9      64
                       0     0     0     0     0     0     0     0     0     0
    11      10      17      18      23      24      43
                       0     0     0     0     0     0     0     0     0     0
    11      12      25      19      29      44
                       0     0     0     0     0     0     0     0     0     0
    11       3      62
                       0     0     0     0     0     0     0     0     0     0
    11      14      31
                       0     0     0     0     0     0     0     0     0     0
    12  303008      63
                       0     0     0     0     0     0     0     0     0     0
    12       9      64
                       0     0     0     0     0     0     0     0     0     0
    12      11      30      43      51
                       0     0     0     0     0     0     0     0     0     0
    12      13      19      29      44
                       0     0     0     0     0     0     0     0     0     0
    12      14      31
                       0     0     0     0     0     0     0     0     0     0
    13  303008      63
                       0     0     0     0     0     0     0     0     0     0
    13       9      64
                       0     0     0     0     0     0     0     0     0     0
    13      11      51
                       0     0     0     0     0     0     0     0     0     0
    13      12      25      43
                       0     0     0     0     0     0     0     0     0     0
    13      14      23      31      44
                       0     0     0     0     0     0     0     0     0     0
    14  303008      63
                       0     0     0     0     0     0     0     0     0     0
    14       9      64
                       0     0     0     0     0     0     0     0     0     0
    14      11      51
                       0     0     0     0     0     0     0     0     0     0
    14      13      23      43
                       0     0     0     0     0     0     0     0     0     0
    14  150020      30      31      34
                       0     0     0     0     0     0     0     0     0     0
    14      15      30
                       0     0     0     0     0     0     0     0     0     0
    14      16      33      44
                       0     0     0     0     0     0     0     0     0     0
    15      18      36      46
                       0     0     0     0     0     0     0     0     0     0
    15      17       7      38      44
                       0     0     0     0     0     0     0     0     0     0
    15      19      10      30      45
                       0     0     0     0     0     0     0     0     0     0
    15  150704      29      31      34      35      23      43
                       0     0     0     0     0     0     0     0     0     0
    15      14      29
                       0     0     0     0     0     0     0     0     0     0
    15      34      55
                       0     0     0     0     0     0     0     0     0     0
    16      14       8      11
                       0     0     0     0     0     0     0     0     0     0
    17      15      38      43
                       0     0     0     0     0     0     0     0     0     0
    17  312596      39
                       0     0     0     0     0     0     0     0     0     0
    17  412021       7
                       0     0     0     0     0     0     0     0     0     0
    17  412597      41      42      44      69
                       0     0     0     0     0     0     0     0     0     0
    17      27      41
                       0     0     0     0     0     0     0     0     0     0
    18      15      38      11      45
                       0     0     0     0     0     0     0     0     0     0
    19      15      10      29      43
                       0     0     0     0     0     0     0     0     0     0
    19  311028      45      36
                       0     0     0     0     0     0     0     0     0     0
    19  311029      46      37
                       0     0     0     0     0     0     0     0     0     0
    19  311030      44       7
                       0     0     0     0     0     0     0     0     0     0
    19      32      45
                       0     0     0     0     0     0     0     0     0     0
    19   35074      49
                       0     0     0     0     0     0     0     0     0     0
    19  211032      49
                       0     0     0     0     0     0     0     0     0     0
    19      74      66
                       0     0     0     0     0     0     0     0     0     0
    20       0       1
                       0     0     0     0     0     0     0     0     0     0
    21       0       1
                       0     0     0     0     0     0     0     0     0     0
    22      79      36      37
                       0     0     0     0     0     0     0     0     0     0
    22   50040      48
                       0     0     0     0     0     0     0     0     0     0
    22   25079      46      48
                       0     0     0     0     0     0     0     0     0     0
    22      22      43      44      46      48
                       0     0     0     0     0     0     0     0     0     0
    22      79      47
                       0     0     0     0     0     0     0     0     0     0
    22   15150      45      49
                       0     0     0     0     0     0     0     0     0     0
    22      22      45      49
                       0     0     0     0     0     0     0     0     0     0
    22      40      50
                       0     0     0     0     0     0     0     0     0     0
    23      67      43      42
                       0     0     0     0     0     0     0     0     0     0
    23      68      44      61
                       0     0     0     0     0     0     0     0     0     0
    23      25      30      31
                       0     0     0     0     0     0     0     0     0     0
    23     648      52
                       0     0     0     0     0     0     0     0     0     0
    24      67      29      11
                       0     0     0     0     0     0     0     0     0     0
    25      23      29      11
                       0     0     0     0     0     0     0     0     0     0
    25  724031      56
                       0     0     0     0     0     0     0     0     0     0
    25      26      56
                       0     0     0     0     0     0     0     0     0     0
    26      25      30
                       0     0     0     0     0     0     0     0     0     0
    26      88      19      44
                       0     0     0     0     0     0     0     0     0     0
    27  312596      39
                       0     0     0     0     0     0     0     0     0     0
    27  412021       7
                       0     0     0     0     0     0     0     0     0     0
    27  412597      41      42      43      69
                       0     0     0     0     0     0     0     0     0     0
    27      17      41
                       0     0     0     0     0     0     0     0     0     0
    27      59      45
                       0     0     0     0     0     0     0     0     0     0
    27      41      44
                       0     0     0     0     0     0     0     0     0     0
    28      19      38      11      46
                       0     0     0     0     0     0     0     0     0     0
    28      33      45      55
                       0     0     0     0     0     0     0     0     0     0
    28      36      30      52
                       0     0     0     0     0     0     0     0     0     0
    29      19      38      11      45
                       0     0     0     0     0     0     0     0     0     0
    30      19      38      11      43
                       0     0     0     0     0     0     0     0     0     0
    30      62      44      29
                       0     0     0     0     0     0     0     0     0     0
    31  524089       1
                       0     0     0     0     0     0     0     0     0     0
    31      90       1
                       0     0     0     0     0     0     0     0     0     0
    32      19       1
                       0     0     0     0     0     0     0     0     0     0
    33       3      65
                       0     0     0     0     0     0     0     0     0     0
    33      28      46
                       0     0     0     0     0     0     0     0     0     0
    33      34      43      53      54
                       0     0     0     0     0     0     0     0     0     0
    33      35      44
                       0     0     0     0     0     0     0     0     0     0
    33  159302      71
                       0     0     0     0     0     0     0     0     0     0
    33     100      71
                       0     0     0     0     0     0     0     0     0     0
    34      33      30      55
                       0     0     0     0     0     0     0     0     0     0
    34      15      29
                       0     0     0     0     0     0     0     0     0     0
    34     145      46
                       0     0     0     0     0     0     0     0     0     0
    35      33      43      55
                       0     0     0     0     0     0     0     0     0     0
    35      20      39
                       0     0     0     0     0     0     0     0     0     0
    36      37      43      17
                       0     0     0     0     0     0     0     0     0     0
    36      28      29      52
                       0     0     0     0     0     0     0     0     0     0
    36      39      44
                       0     0     0     0     0     0     0     0     0     0
    36      65      70
                       0     0     0     0     0     0     0     0     0     0
    37      36      44      17
                       0     0     0     0     0     0     0     0     0     0
    37      38      30      31      56
                       0     0     0     0     0     0     0     0     0     0
    38      37      56      29      11
                       0     0     0     0     0     0     0     0     0     0
    38     595      60      14      30       4       5
                       0     0     0     0     0     0     0     0     0     0
    39      36      43      23
                       0     0     0     0     0     0     0     0     0     0
    39      64      30      52      58
                       0     0     0     0     0     0     0     0     0     0
    39      65      70
                       0     0     0     0     0     0     0     0     0     0
    40      22      36
                       0     0     0     0     0     0     0     0     0     0
    40      59      46
                       0     0     0     0     0     0     0     0     0     0
    40      22      45
                       0     0     0     0     0     0     0     0     0     0
    41      42      46      29      23      56
                       0     0     0     0     0     0     0     0     0     0
    41      27      43
                       0     0     0     0     0     0     0     0     0     0
    41      59      45
                       0     0     0     0     0     0     0     0     0     0
    41      60      44      17
                       0     0     0     0     0     0     0     0     0     0
    42      41      29
                       0     0     0     0     0     0     0     0     0     0
    42      42      45
                       0     0     0     0     0     0     0     0     0     0
    42      43      43
                       0     0     0     0     0     0     0     0     0     0
    42      45      46
                       0     0     0     0     0     0     0     0     0     0
    42      80      44
                       0     0     0     0     0     0     0     0     0     0
    43      42      44
                       0     0     0     0     0     0     0     0     0     0
    43      44      46
                       0     0     0     0     0     0     0     0     0     0
    43      45      43
                       0     0     0     0     0     0     0     0     0     0
    44      43      43
                       0     0     0     0     0     0     0     0     0     0
    44      48      30
                       0     0     0     0     0     0     0     0     0     0
    44      50      46
                       0     0     0     0     0     0     0     0     0     0
    44      82      45
                       0     0     0     0     0     0     0     0     0     0
    45      42      44
                       0     0     0     0     0     0     0     0     0     0
    45      43      45
                       0     0     0     0     0     0     0     0     0     0
    45      46      43
                       0     0     0     0     0     0     0     0     0     0
    45      47      46
                       0     0     0     0     0     0     0     0     0     0
    45      87      29      30
                       0     0     0     0     0     0     0     0     0     0
    46      45      44      11
                       0     0     0     0     0     0     0     0     0     0
    47      45      43      11
                       0     0     0     0     0     0     0     0     0     0
    48      44      29      11
                       0     0     0     0     0     0     0     0     0     0
    49      50      43
                       0     0     0     0     0     0     0     0     0     0
    49      51      44
                       0     0     0     0     0     0     0     0     0     0
    50      44      43
                       0     0     0     0     0     0     0     0     0     0
    50      49      44
                       0     0     0     0     0     0     0     0     0     0
    50      51      30
                       0     0     0     0     0     0     0     0     0     0
    50      52      46
                       0     0     0     0     0     0     0     0     0     0
    51      49      44
                       0     0     0     0     0     0     0     0     0     0
    51      50      29
                       0     0     0     0     0     0     0     0     0     0
    51      52      43
                       0     0     0     0     0     0     0     0     0     0
    51      53      46
                       0     0     0     0     0     0     0     0     0     0
    52      50      44
                       0     0     0     0     0     0     0     0     0     0
    52      51      43
                       0     0     0     0     0     0     0     0     0     0
    52      52      46
                       0     0     0     0     0     0     0     0     0     0
    52      53      29
                       0     0     0     0     0     0     0     0     0     0
    52      55      45
                       0     0     0     0     0     0     0     0     0     0
    52      86      30
                       0     0     0     0     0     0     0     0     0     0
    53      51      44
                       0     0     0     0     0     0     0     0     0     0
    53      52      45
                       0     0     0     0     0     0     0     0     0     0
    53      54      46
                       0     0     0     0     0     0     0     0     0     0
    54      53      44      11
                       0     0     0     0     0     0     0     0     0     0
    55      52      44
                       0     0     0     0     0     0     0     0     0     0
    55      55      45
                       0     0     0     0     0     0     0     0     0     0
    55      56      30
                       0     0     0     0     0     0     0     0     0     0
    55      57      43
                       0     0     0     0     0     0     0     0     0     0
    56      55      29      11
                       0     0     0     0     0     0     0     0     0     0
    57      13      30      56
                       0     0     0     0     0     0     0     0     0     0
    57      55      44
                       0     0     0     0     0     0     0     0     0     0
    57      58      46
                       0     0     0     0     0     0     0     0     0     0
    57      83      45
                       0     0     0     0     0     0     0     0     0     0
    57      84      43
                       0     0     0     0     0     0     0     0     0     0
    58      57      43      11
                       0     0     0     0     0     0     0     0     0     0
    59      27      44
                       0     0     0     0     0     0     0     0     0     0
    59      41      43
                       0     0     0     0     0     0     0     0     0     0
    59      40      45
                       0     0     0     0     0     0     0     0     0     0
    60      41      43      29      17
                       0     0     0     0     0     0     0     0     0     0
    60      61      44
                       0     0     0     0     0     0     0     0     0     0
    60      62      45      30      52
                       0     0     0     0     0     0     0     0     0     0
    61      60      43
                       0     0     0     0     0     0     0     0     0     0
    61      62      45
                       0     0     0     0     0     0     0     0     0     0
    61  100107      46
                       0     0     0     0     0     0     0     0     0     0
    62      60      44
                       0     0     0     0     0     0     0     0     0     0
    62      63      45
                       0     0     0     0     0     0     0     0     0     0
    62      30      43
                       0     0     0     0     0     0     0     0     0     0
    62      61      46
                       0     0     0     0     0     0     0     0     0     0
    63      62      46      11
                       0     0     0     0     0     0     0     0     0     0
    64      39      29      56      59
                       0     0     0     0     0     0     0     0     0     0
    64      65      44      70
                       0     0     0     0     0     0     0     0     0     0
    64     103      45      74
                       0     0     0     0     0     0     0     0     0     0
    64     106      43
                       0     0     0     0     0     0     0     0     0     0
    65      64      43
                       0     0     0     0     0     0     0     0     0     0
    65      66      44
                       0     0     0     0     0     0     0     0     0     0
    65   80556      46
                       0     0     0     0     0     0     0     0     0     0
    65      68      61
                       0     0     0     0     0     0     0     0     0     0
    65   80556      29
                       0     0     0     0     0     0     0     0     0     0
    65      70      66
                       0     0     0     0     0     0     0     0     0     0
    65   50070      29
                       0     0     0     0     0     0     0     0     0     0
    65      39      29
                       0     0     0     0     0     0     0     0     0     0
    65   60556      45
                       0     0     0     0     0     0     0     0     0     0
    65   75072      45
                       0     0     0     0     0     0     0     0     0     0
    65      71      45
                       0     0     0     0     0     0     0     0     0     0
    65   80556      30
                       0     0     0     0     0     0     0     0     0     0
    65     106      30
                       0     0     0     0     0     0     0     0     0     0
    66      65      47
                       0     0     0     0     0     0     0     0     0     0
    66      67      44
                       0     0     0     0     0     0     0     0     0     0
    66   80556      46
                       0     0     0     0     0     0     0     0     0     0
    66      77      25
                       0     0     0     0     0     0     0     0     0     0
    66      96      43
                       0     0     0     0     0     0     0     0     0     0
    66   50556      50
                       0     0     0     0     0     0     0     0     0     0
    66      97      72
                       0     0     0     0     0     0     0     0     0     0
    67      66      43
                       0     0     0     0     0     0     0     0     0     0
    67      23      44      42
                       0     0     0     0     0     0     0     0     0     0
    67      24      30      31
                       0     0     0     0     0     0     0     0     0     0
    68      23      46
                       0     0     0     0     0     0     0     0     0     0
    68      69      29      56      66
                       0     0     0     0     0     0     0     0     0     0
    68      65      45
                       0     0     0     0     0     0     0     0     0     0
    69      68      30      61
                       0     0     0     0     0     0     0     0     0     0
    69  331120      46
                       0     0     0     0     0     0     0     0     0     0
    69     119      46
                       0     0     0     0     0     0     0     0     0     0
    69     109      45
                       0     0     0     0     0     0     0     0     0     0
    69     113      75
                       0     0     0     0     0     0     0     0     0     0
    70      71      45
                       0     0     0     0     0     0     0     0     0     0
    70      65      30      23
                       0     0     0     0     0     0     0     0     0     0
    70     111      46
                       0     0     0     0     0     0     0     0     0     0
    71      65      48
                       0     0     0     0     0     0     0     0     0     0
    71      70      46
                       0     0     0     0     0     0     0     0     0     0
    71     110      45
                       0     0     0     0     0     0     0     0     0     0
    72      65      70
                       0     0     0     0     0     0     0     0     0     0
    72     118      49
                       0     0     0     0     0     0     0     0     0     0
    72      73      45
                       0     0     0     0     0     0     0     0     0     0
    72      97      48      72
                       0     0     0     0     0     0     0     0     0     0
    73      72      46      17      11
                       0     0     0     0     0     0     0     0     0     0
    74      19      43
                       0     0     0     0     0     0     0     0     0     0
    74  331120      44
                       0     0     0     0     0     0     0     0     0     0
    74     121      44
                       0     0     0     0     0     0     0     0     0     0
    74      75      30
                       0     0     0     0     0     0     0     0     0     0
    75      76      46
                       0     0     0     0     0     0     0     0     0     0
    75      77      45
                       0     0     0     0     0     0     0     0     0     0
    76      75      45
                       0     0     0     0     0     0     0     0     0     0
    77      75      43
                       0     0     0     0     0     0     0     0     0     0
    77      78      44
                       0     0     0     0     0     0     0     0     0     0
    77      66      45      17
                       0     0     0     0     0     0     0     0     0     0
    78      77      46
                       0     0     0     0     0     0     0     0     0     0
    79     150      36
                       0     0     0     0     0     0     0     0     0     0
    79      40      37
                       0     0     0     0     0     0     0     0     0     0
    79      22      48
                       0     0     0     0     0     0     0     0     0     0
    79   25150      49      50
                       0     0     0     0     0     0     0     0     0     0
    79   25022      43      44      45      46      49      50
                       0     0     0     0     0     0     0     0     0     0
    79      79      43      44      45      46      49      50
                       0     0     0     0     0     0     0     0     0     0
    80      42      45
                       0     0     0     0     0     0     0     0     0     0
    80      80      44
                       0     0     0     0     0     0     0     0     0     0
    80      80      46
                       0     0     0     0     0     0     0     0     0     0
    80      81      43
                       0     0     0     0     0     0     0     0     0     0
    81      80      44      11
                       0     0     0     0     0     0     0     0     0     0
    82      44      46      11
                       0     0     0     0     0     0     0     0     0     0
    83      57      46
                       0     0     0     0     0     0     0     0     0     0
    83      84      43
                       0     0     0     0     0     0     0     0     0     0
    83      85      44
                       0     0     0     0     0     0     0     0     0     0
    84      57      45
                       0     0     0     0     0     0     0     0     0     0
    84      83      44
                       0     0     0     0     0     0     0     0     0     0
    84     114      50
                       0     0     0     0     0     0     0     0     0     0
    85      83      43      11
                       0     0     0     0     0     0     0     0     0     0
    86      52      29      11
                       0     0     0     0     0     0     0     0     0     0
    87      45      29      30
                       0     0     0     0     0     0     0     0     0     0
    88      25      30      56      43
                       0     0     0     0     0     0     0     0     0     0
    88      20      39
                       0     0     0     0     0     0     0     0     0     0
    88      92      44      27
                       0     0     0     0     0     0     0     0     0     0
    89      25       1
                       0     0     0     0     0     0     0     0     0     0
    90      23       1
                       0     0     0     0     0     0     0     0     0     0
    91      95      45      73      23
                       0     0     0     0     0     0     0     0     0     0
    91      72      30      56
                       0     0     0     0     0     0     0     0     0     0
    92      88      46
                       0     0     0     0     0     0     0     0     0     0
    92      93      43
                       0     0     0     0     0     0     0     0     0     0
    92      94      45
                       0     0     0     0     0     0     0     0     0     0
    93      92      46      27      11
                       0     0     0     0     0     0     0     0     0     0
    94      92      46      27      23
                       0     0     0     0     0     0     0     0     0     0
    94  309095      45       3      73
                       0     0     0     0     0     0     0     0     0     0
    94     611      45
                       0     0     0     0     0     0     0     0     0     0
    95      94      46      11
                       0     0     0     0     0     0     0     0     0     0
    95      92      27
                       0     0     0     0     0     0     0     0     0     0
    95      91      44
                       0     0     0     0     0     0     0     0     0     0
    96      66      44      11
                       0     0     0     0     0     0     0     0     0     0
    97      66      48
                       0     0     0     0     0     0     0     0     0     0
    97      72      44      17
                       0     0     0     0     0     0     0     0     0     0
    97      98      29      45      73
                       0     0     0     0     0     0     0     0     0     0
    98      97      46      72
                       0     0     0     0     0     0     0     0     0     0
    98      99      44
                       0     0     0     0     0     0     0     0     0     0
    99      98      50      73
                       0     0     0     0     0     0     0     0     0     0
    99     301      43      23
                       0     0     0     0     0     0     0     0     0     0
    99     100      43
                       0     0     0     0     0     0     0     0     0     0
   100     301      44      23      11
                       0     0     0     0     0     0     0     0     0     0
   100      99      44
                       0     0     0     0     0     0     0     0     0     0
   100  159302      71
                       0     0     0     0     0     0     0     0     0     0
   100      33      71
                       0     0     0     0     0     0     0     0     0     0
   100     101      47      22
                       0     0     0     0     0     0     0     0     0     0
   101     100      46      71      11
                       0     0     0     0     0     0     0     0     0     0
   101     141      29      56
                       0     0     0     0     0     0     0     0     0     0
   102     103      30      74      11
                       0     0     0     0     0     0     0     0     0     0
   103     102      29      38
                       0     0     0     0     0     0     0     0     0     0
   103     104      30
                       0     0     0     0     0     0     0     0     0     0
   103  114618      46
                       0     0     0     0     0     0     0     0     0     0
   103  115619      46
                       0     0     0     0     0     0     0     0     0     0
   103      64      46
                       0     0     0     0     0     0     0     0     0     0
   104     103      29      74
                       0     0     0     0     0     0     0     0     0     0
   104     105      30
                       0     0     0     0     0     0     0     0     0     0
   105     104      29      11
                       0     0     0     0     0     0     0     0     0     0
   105     103      74
                       0     0     0     0     0     0     0     0     0     0
   106      64      29
                       0     0     0     0     0     0     0     0     0     0
   106      65      44
                       0     0     0     0     0     0     0     0     0     0
   106     108      43
                       0     0     0     0     0     0     0     0     0     0
   107     131      46
                       0     0     0     0     0     0     0     0     0     0
   107     132      49
                       0     0     0     0     0     0     0     0     0     0
   107     133      47
                       0     0     0     0     0     0     0     0     0     0
   107     134      48
                       0     0     0     0     0     0     0     0     0     0
   107     135      29
                       0     0     0     0     0     0     0     0     0     0
   107     136      50
                       0     0     0     0     0     0     0     0     0     0
   107     137      43
                       0     0     0     0     0     0     0     0     0     0
   107     138      44
                       0     0     0     0     0     0     0     0     0     0
   107     139      45
                       0     0     0     0     0     0     0     0     0     0
   107      61      30
                       0     0     0     0     0     0     0     0     0     0
   108   95556      43      45      46      47      48      49      50      29
                       0     0     0     0     0     0     0     0     0     0
   108     106      43
                       0     0     0     0     0     0     0     0     0     0
   108     626      44
                       0     0     0     0     0     0     0     0     0     0
   109      69      46
                       0     0     0     0     0     0     0     0     0     0
   109     113      45      75
                       0     0     0     0     0     0     0     0     0     0
   110      71      44
                       0     0     0     0     0     0     0     0     0     0
   110      20      39
                       0     0     0     0     0     0     0     0     0     0
   111      70      45
                       0     0     0     0     0     0     0     0     0     0
   111   40050      30      39      56
                       0     0     0     0     0     0     0     0     0     0
   111   50053      30
                       0     0     0     0     0     0     0     0     0     0
   111      45      30
                       0     0     0     0     0     0     0     0     0     0
   112     131      49
                       0     0     0     0     0     0     0     0     0     0
   112     132      45
                       0     0     0     0     0     0     0     0     0     0
   112     133      43
                       0     0     0     0     0     0     0     0     0     0
   112     134      50
                       0     0     0     0     0     0     0     0     0     0
   112     135      48
                       0     0     0     0     0     0     0     0     0     0
   112     136      47
                       0     0     0     0     0     0     0     0     0     0
   112     137      44
                       0     0     0     0     0     0     0     0     0     0
   112     138      30
                       0     0     0     0     0     0     0     0     0     0
   112     139      29
                       0     0     0     0     0     0     0     0     0     0
   112     140      46
                       0     0     0     0     0     0     0     0     0     0
   113     109      46      11     109
                       0     0     0     0     0     0     0     0     0     0
   114      84      48
                       0     0     0     0     0     0     0     0     0     0
   115     116      49
                       0     0     0     0     0     0     0     0     0     0
   116     115      47
                       0     0     0     0     0     0     0     0     0     0
   116     593      30
                       0     0     0     0     0     0     0     0     0     0
   117     118      49
                       0     0     0     0     0     0     0     0     0     0
   117  233660      41      42      69      47
                       0     0     0     0     0     0     0     0     0     0
   117  332661      41
                       0     0     0     0     0     0     0     0     0     0
   117     303      41
                       0     0     0     0     0     0     0     0     0     0
   117  332021      39
                       0     0     0     0     0     0     0     0     0     0
   117     596      39
                       0     0     0     0     0     0     0     0     0     0
   118      72      30
                       0     0     0     0     0     0     0     0     0     0
   118     117      29
                       0     0     0     0     0     0     0     0     0     0
   119      69      45      11
                       0     0     0     0     0     0     0     0     0     0
   119     653      43       7
                       0     0     0     0     0     0     0     0     0     0
   120      69      45
                       0     0     0     0     0     0     0     0     0     0
   120      74      43
                       0     0     0     0     0     0     0     0     0     0
   121      74      43      11
                       0     0     0     0     0     0     0     0     0     0
   121     653      45       7
                       0     0     0     0     0     0     0     0     0     0
   122     123      47
                       0     0     0     0     0     0     0     0     0     0
   122  233660      41      42      69      49
                       0     0     0     0     0     0     0     0     0     0
   122     303      41
                       0     0     0     0     0     0     0     0     0     0
   122     596      39
                       0     0     0     0     0     0     0     0     0     0
   122     124      77
                       0     0     0     0     0     0     0     0     0     0
   122     126      28
                       0     0     0     0     0     0     0     0     0     0
   122     129      40
                       0     0     0     0     0     0     0     0     0     0
   123     122      44
                       0     0     0     0     0     0     0     0     0     0
   123     124      43      77
                       0     0     0     0     0     0     0     0     0     0
   123     126      28
                       0     0     0     0     0     0     0     0     0     0
   123     129      40
                       0     0     0     0     0     0     0     0     0     0
   124     123      44
                       0     0     0     0     0     0     0     0     0     0
   124     125      47      36
                       0     0     0     0     0     0     0     0     0     0
   124     128      48      37      30
                       0     0     0     0     0     0     0     0     0     0
   124     126      28
                       0     0     0     0     0     0     0     0     0     0
   124     129      40
                       0     0     0     0     0     0     0     0     0     0
   125     124      46      77
                       0     0     0     0     0     0     0     0     0     0
   125     126      45      28
                       0     0     0     0     0     0     0     0     0     0
   125     127      43      17
                       0     0     0     0     0     0     0     0     0     0
   126     125      46      23      11
                       0     0     0     0     0     0     0     0     0     0
   126     124      77
                       0     0     0     0     0     0     0     0     0     0
   126     610      30      39
                       0     0     0     0     0     0     0     0     0     0
   127     125      44      11      17
                       0     0     0     0     0     0     0     0     0     0
   127     124      77
                       0     0     0     0     0     0     0     0     0     0
   127     126      28
                       0     0     0     0     0     0     0     0     0     0
   128     124      45      29      77
                       0     0     0     0     0     0     0     0     0     0
   128     129      46      30      40
                       0     0     0     0     0     0     0     0     0     0
   128     126      28
                       0     0     0     0     0     0     0     0     0     0
   129     128      44      29
                       0     0     0     0     0     0     0     0     0     0
   129     124      77
                       0     0     0     0     0     0     0     0     0     0
   129     130      43      19      40       3
                       0     0     0     0     0     0     0     0     0     0
   129     126      28
                       0     0     0     0     0     0     0     0     0     0
   130     129      44      11
                       0     0     0     0     0     0     0     0     0     0
   130     124      77
                       0     0     0     0     0     0     0     0     0     0
   130     126      28
                       0     0     0     0     0     0     0     0     0     0
   131     107      44
                       0     0     0     0     0     0     0     0     0     0
   131     132      48
                       0     0     0     0     0     0     0     0     0     0
   131     133      50
                       0     0     0     0     0     0     0     0     0     0
   131     134      49
                       0     0     0     0     0     0     0     0     0     0
   131     135      47
                       0     0     0     0     0     0     0     0     0     0
   131     136      29
                       0     0     0     0     0     0     0     0     0     0
   131     137      30
                       0     0     0     0     0     0     0     0     0     0
   131     138      45
                       0     0     0     0     0     0     0     0     0     0
   131     139      46
                       0     0     0     0     0     0     0     0     0     0
   131     112      43
                       0     0     0     0     0     0     0     0     0     0
   132     107      50
                       0     0     0     0     0     0     0     0     0     0
   132     131      29
                       0     0     0     0     0     0     0     0     0     0
   132     133      45
                       0     0     0     0     0     0     0     0     0     0
   132     134      46
                       0     0     0     0     0     0     0     0     0     0
   132     135      44
                       0     0     0     0     0     0     0     0     0     0
   132     136      49
                       0     0     0     0     0     0     0     0     0     0
   132     137      47
                       0     0     0     0     0     0     0     0     0     0
   132     138      43
                       0     0     0     0     0     0     0     0     0     0
   132     139      30
                       0     0     0     0     0     0     0     0     0     0
   132     112      48
                       0     0     0     0     0     0     0     0     0     0
   133     107      29
                       0     0     0     0     0     0     0     0     0     0
   133     131      30
                       0     0     0     0     0     0     0     0     0     0
   133     132      44
                       0     0     0     0     0     0     0     0     0     0
   133     134      47
                       0     0     0     0     0     0     0     0     0     0
   133     135      49
                       0     0     0     0     0     0     0     0     0     0
   133     136      43
                       0     0     0     0     0     0     0     0     0     0
   133     137      45
                       0     0     0     0     0     0     0     0     0     0
   133     138      50
                       0     0     0     0     0     0     0     0     0     0
   133     139      48
                       0     0     0     0     0     0     0     0     0     0
   133     112      46
                       0     0     0     0     0     0     0     0     0     0
   134     107      47
                       0     0     0     0     0     0     0     0     0     0
   134     131      45
                       0     0     0     0     0     0     0     0     0     0
   134     132      50
                       0     0     0     0     0     0     0     0     0     0
   134     133      48
                       0     0     0     0     0     0     0     0     0     0
   134     135      43
                       0     0     0     0     0     0     0     0     0     0
   134     136      30
                       0     0     0     0     0     0     0     0     0     0
   134     137      46
                       0     0     0     0     0     0     0     0     0     0
   134     138      29
                       0     0     0     0     0     0     0     0     0     0
   134     139      44
                       0     0     0     0     0     0     0     0     0     0
   134     112      49
                       0     0     0     0     0     0     0     0     0     0
   135     107      45
                       0     0     0     0     0     0     0     0     0     0
   135     131      48
                       0     0     0     0     0     0     0     0     0     0
   135     132      30
                       0     0     0     0     0     0     0     0     0     0
   135     133      46
                       0     0     0     0     0     0     0     0     0     0
   135     134      43
                       0     0     0     0     0     0     0     0     0     0
   135     136      44
                       0     0     0     0     0     0     0     0     0     0
   135     137      49
                       0     0     0     0     0     0     0     0     0     0
   135     138      47
                       0     0     0     0     0     0     0     0     0     0
   135     139      50
                       0     0     0     0     0     0     0     0     0     0
   135     112      29
                       0     0     0     0     0     0     0     0     0     0
   136     107      43
                       0     0     0     0     0     0     0     0     0     0
   136     131      44
                       0     0     0     0     0     0     0     0     0     0
   136     132      29
                       0     0     0     0     0     0     0     0     0     0
   136     133      49
                       0     0     0     0     0     0     0     0     0     0
   136     134      30
                       0     0     0     0     0     0     0     0     0     0
   136     135      46
                       0     0     0     0     0     0     0     0     0     0
   136     137      50
                       0     0     0     0     0     0     0     0     0     0
   136     138      48
                       0     0     0     0     0     0     0     0     0     0
   136     139      47
                       0     0     0     0     0     0     0     0     0     0
   136     112      45
                       0     0     0     0     0     0     0     0     0     0
   137     107      48
                       0     0     0     0     0     0     0     0     0     0
   137     131      47
                       0     0     0     0     0     0     0     0     0     0
   137     132      46
                       0     0     0     0     0     0     0     0     0     0
   137     133      30
                       0     0     0     0     0     0     0     0     0     0
   137     134      29
                       0     0     0     0     0     0     0     0     0     0
   137     135      50
                       0     0     0     0     0     0     0     0     0     0
   137     136      45
                       0     0     0     0     0     0     0     0     0     0
   137     138      49
                       0     0     0     0     0     0     0     0     0     0
   137     139      43
                       0     0     0     0     0     0     0     0     0     0
   137     112      44
                       0     0     0     0     0     0     0     0     0     0
   138     107      30
                       0     0     0     0     0     0     0     0     0     0
   138     131      43
                       0     0     0     0     0     0     0     0     0     0
   138     132      47
                       0     0     0     0     0     0     0     0     0     0
   138     133      29
                       0     0     0     0     0     0     0     0     0     0
   138     134      44
                       0     0     0     0     0     0     0     0     0     0
   138     135      45
                       0     0     0     0     0     0     0     0     0     0
   138     136      46
                       0     0     0     0     0     0     0     0     0     0
   138     137      48
                       0     0     0     0     0     0     0     0     0     0
   138     139      49
                       0     0     0     0     0     0     0     0     0     0
   138     112      50
                       0     0     0     0     0     0     0     0     0     0
   139     107      49
                       0     0     0     0     0     0     0     0     0     0
   139     131      50
                       0     0     0     0     0     0     0     0     0     0
   139     132      43
                       0     0     0     0     0     0     0     0     0     0
   139     133      44
                       0     0     0     0     0     0     0     0     0     0
   139     134      45
                       0     0     0     0     0     0     0     0     0     0
   139     135      30
                       0     0     0     0     0     0     0     0     0     0
   139     136      48
                       0     0     0     0     0     0     0     0     0     0
   139     137      29
                       0     0     0     0     0     0     0     0     0     0
   139     138      46
                       0     0     0     0     0     0     0     0     0     0
   139     112      47
                       0     0     0     0     0     0     0     0     0     0
   140     112      45      11
                       0     0     0     0     0     0     0     0     0     0
   141     101      30
                       0     0     0     0     0     0     0     0     0     0
   141     142      45
                       0     0     0     0     0     0     0     0     0     0
   142     141      46
                       0     0     0     0     0     0     0     0     0     0
   142     143      50      29      34
                       0     0     0     0     0     0     0     0     0     0
   142     148      44
                       0     0     0     0     0     0     0     0     0     0
   143     142      48      30      34
                       0     0     0     0     0     0     0     0     0     0
   143     144      47       3      19      59
                       0     0     0     0     0     0     0     0     0     0
   144     143      49      11
                       0     0     0     0     0     0     0     0     0     0
   144     702      43      44      45      46      47      48      50
                       0     0     0     0     0     0     0     0     0     0
   145      34      29      30      44      45      46      47      48
                       0     0     0     0     0     0     0     0     0     0
   145     146      43
                       0     0     0     0     0     0     0     0     0     0
   146     147      48
                       0     0     0     0     0     0     0     0     0     0
   146   50145      29      30      44      45      43      46      49
                       0     0     0     0     0     0     0     0     0     0
   146      34      47      50
                       0     0     0     0     0     0     0     0     0     0
   147     146      50
                       0     0     0     0     0     0     0     0     0     0
   148     142      46
                       0     0     0     0     0     0     0     0     0     0
   148  141149      29      56
                       0     0     0     0     0     0     0     0     0     0
   148     703      29      56
                       0     0     0     0     0     0     0     0     0     0
   149  141148      30      56
                       0     0     0     0     0     0     0     0     0     0
   149     703      30      56
                       0     0     0     0     0     0     0     0     0     0
   150      22      37
                       0     0     0     0     0     0     0     0     0     0
   150     150      48
                       0     0     0     0     0     0     0     0     0     0
   150   25150      49      50
                       0     0     0     0     0     0     0     0     0     0
   150   15022      43      44      45      46      49      50
                       0     0     0     0     0     0     0     0     0     0
   150      79      43      44      45      46      49      50
                       0     0     0     0     0     0     0     0     0     0
    -1
     4
     2ROAD
     3ENTER
     4UPSTR
     5DOWNS
     6FORES
     7FORWA
     7ONWAR
     8BACK
     8RETUR
     9VALLE
    10STAIR
    11OUT
    11OUTSI
    11EXIT
    11LEAVE
    12BUILD
    12HOUSE
    13GULLY
    14STREA
    15ROCK
    16BED
    17CRAWL
    18COBBL
    19INSID
    19IN
    20SURFA
    21NULL
    21NOWHE
    22DARK
    23PASSA
    23TUNNE
    24LOW
    25CANYO
    26AWKWA
    27GIANT
    28VIEW
    29UPWAR
    29UP
    29U
    29ABOVE
    29ASCEN
    30D
    30DOWNW
    30DOWN
    30DESCE
    31PIT
    32OUTDO
    33CRACK
    34STEPS
    35DOME
    36LEFT
    37RIGHT
    38HALL
    39JUMP
    40BARRE
    41OVER
    42ACROS
    43EAST
    43E
    44WEST
    44W
    45NORTH
    45N
    46SOUTH
    46S
    47NE
    48SE
    49SW
    50NW
    51DEBRI
    52HOLE
    53WALL
    54BROKE
    55Y2
    56CLIMB
    57LOOK
    57TOUCH
    57DESCR
    58FLOOR
    59ROOM
    60SLIT
    61SLAB
    61SLABR
    62XYZZY
    63DEPRE
    64ENTRA
    65PLUGH
    66SECRE
    67CAVE
    69CROSS
    70BEDQU
    71PLOVE
    72ORIEN
    73CAVER
    74SHELL
    75RESER
    76MAIN
    76OFFIC
    77FORK
  1001KEYS
  1001KEY
  1002LAMP
  1002LANTE
  1003GRATE
  1004CAGE
  1005ROD
  1006ROD     (MUST BE NEXT OBJECT AFTER "REAL" ROD)
  1007STEPS
  1008BIRD
  1009DOOR
  1010PILLO
  1010VELVE
  1011SNAKE
  1012FISSU
  1013TABLE
  1014CLAM
  1015OYSTE
  1016MAGAZ
  1016ISSUE
  1016SPELU
  1016"SPEL
  1017DWARF
  1017DWARV
  1018KNIFE
  1018KNIVE
  1019FOOD
  1020BOTTL
  1020JAR
  1021WATER
  1021H2O
  1022OIL
  1023MIRRO
  1024PLANT
  1024BEANS
  1025PLANT   (MUST BE NEXT OBJECT AFTER "REAL" PLANT)
  1026STALA
  1027SHADO
  1027FIGUR
  1028AXE
  1029DRAWI
  1030PIRAT
  1031DRAGO
  1032CHASM
  1033TROLL
  1034TROLL   (MUST BE NEXT OBJECT AFTER "REAL" TROLL)
                       0     0     0     0     0     0     0     0     0     0
  1035BEAR
                       0     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
                       0     0     0     0     0     0     0     0     0     0
  1037GEYSE   (SAME AS VOLCANO)
  1038MACHI
  1038VENDI
  1039BATTE
  1040CARPE
  1040MOSS
  1041CRAMP
  1050GOLD
  1050NUGGE
  1051DIAMO
  1052SILVE
  1052BARS
  1053JEWEL
  1054COINS
  1055CHEST
  1055BOX
  1055TREAS
  1056EGGS
  1056EGG
  1056NEST
  1057TRIDENT
  1058VASE
  1058MING
  1058SHARD
  1058POTTE
  1059EMERA
  1060PLATI
  1060PYRAM
  1061PEARL
  1062RUG
  1062PERSI
  1063SPICE
  1064CHAIN
  1065IRIDI
  1065CRUCI
  1066MUSHR
  1066CRYST
  2001TAKE
  2001CATCH
  2001STEAL
  2001CAPTU
  2001GET
  2001G
  2002DROP
  2002RELEA
  2002FREE
  2002DISCA
  2002DUMP
  2003SAY
  2003CHANT
  2004UNLOC
  2004OPEN
  2005NOTHI
  2006LOCK
  2006CLOSE
  2007LIGHT
  2007ON
  2008EXTIN
  2008OFF
  2009WAVE
  2009SHAKE
  2009SWING
  2010CALM
  2010PLACA
  2010TAME
  2011WALK
  2011RUN
  2011TRAVE
  2011GO
  2011PROCE
  2011CONTI
  2011EXPLO
  2011GOTO
  2011FOLLO
  2011TURN
  2012ATTAC
  2012KILL
  2012FIGHT
  2012HIT
  2012STRIK
  2012SLAY
  2013POUR
  2014EAT
  2014DEVOU
  2015DRINK
  2016RUB
  2017THROW
  2017TOSS
  2018QUIT
  2018Q
  2019FIND
  2019WHERE
  2020INVEN
  2021FEED
  2022FILL
  2023BLAST
  2023DETON
  2024SCORE
  2025FEE
  2025FIE
  2025FOE
  2025FOO
  2025FUM
  2026BRIEF
  2027READ
  2028BREAK
  2028SHATT
  2028SMASH
  2029WAKE
  2029DISTU
  2030SUSPE
  2030PAUSE
  2030SAVE
  2031HOURS
  3001FEE
  3002FIE
  3003FOE
  3004FOO
  3005FUM
  3050SESAM
  3050OPENS
  3050ABRA
  3050ABRAC
  3050SHAZA
  3050HOCUS
  3050POCUS
  3051HELP
  3064TREE
  3064TREES
  3066DIG
  3066EXCAV
  3068LOST
  3069MIST
  3079FUCK
  3139STOP
  3142INFO
  3142INFOR
  3147SWIM
    -1
     5
     1set of keys
     0there are some keys on the ground here.
     2brass lantern
     0there is a shiny brass lamp nearby.
   100there is a lamp shining nearby.
     3*grate
     0the grate is locked.
   100the grate is open.
     4wicker cage
     0there is a small wicker cage discarded nearby.
     5black rod
     0a three foot black rod with a rusty star on an end lies nearby.
     6black rod
     0a three foot black rod with a rusty mark on an end lies nearby.
     7*steps
     0rough stone steps lead down the pit.
   100rough stone steps lead up the dome.
     8little bird in cage
     0a cheerful little bird is sitting here singing.
   100there is a little bird in the cage.
     9*rusty door
     0the way north is barred by a massive, rusty, iron door.
   100the way north leads through a massive, rusty, iron door.
    10velvet pillow
     0a small velvet pillow lies on the floor.
    11*snake
     0a huge green fierce snake bars the way!
   100>$<  (chased away)
    12*fissure
     0>$<
   100a crystal bridge now spans the fissure.
   200the crystal bridge has vanished!
    13*stone tablet
     0a massive stone tablet imbedded in the wall reads:
     0"congratulations on bringing light into the dark-room!"
    14giant clam  >grunt!<
     0there is an enormous clam here with its shell tightly closed.
    15giant oyster  >groan!<
     0there is an enormous oyster here with its shell tightly closed.
   100interesting.  There seems to be something written on the underside of
   100the oyster.
    16"spelunker today"
     0there are a few recent issues of "spelunker today" magazine here.
    19tasty food
     0there is food here.
    20small bottle
     0there is a bottle of water here.
   100there is an empty bottle here.
   200there is a bottle of oil here.
    21water in the bottle
    22oil in the bottle
    23*mirror
     0>$<
    24*plant
     0there is a tiny little plant in the pit, murmuring "water, water, ..."
   100the plant spurts into furious growth for a few seconds.
   200there is a 12-foot-tall beanstalk stretching up out of the pit,
   200bellowing "water!! water!!"
   300the plant grows explosively, almost filling the bottom of the pit.
   400there is a gigantic beanstalk stretching all the way up to the hole.
   500You've over-watered the plant!  it's shriveling up!  it's, it's...
    25*phony plant (seen in twopit room only when tall enough)
     0>$<
   100the top of a 12-foot-tall beanstalk is poking out of the west pit.
   200there is a huge beanstalk growing out of the west pit up to the hole.
    26*stalactite
     0>$<
    27*shadowy figure
     0the shadowy figure seems to be trying to attract your attention.
    28dwarf's axe
     0there is a little axe here.
   100there is a little axe lying beside the bear.
    29*cave drawings
     0>$<
    30*pirate
     0>$<
    31*dragon
     0a huge green fierce dragon bars the way!
   100congratulations!  you have just vanquished a dragon with your bare
   100hands!  (unbelievable, isn't it?)
   200the body of a huge green dead dragon is lying off to one side.
    32*chasm
     0a rickety wooden bridge extends across the chasm, vanishing into the
     0mist.  A sign posted on the bridge reads, "stop! pay troll!"
   100the wreckage of a bridge (and a dead bear) can be seen at the bottom
   100of the chasm.
    33*troll
     0a burly troll stands by the bridge and insists you throw him a
     0treasure before you may cross.
   100the troll steps out from beneath the bridge and blocks your way.
   200>$<  (chased away)
    34*phony troll
     0the troll is nowhere to be seen.
    35>$<  (bear uses rtext 141)
     0there is a ferocious cave bear eying you from the far end of the room!
   100there is a gentle cave bear sitting placidly in one corner.
   200there is a contented-looking bear wandering about nearby.
   300>$<  (dead)
    36*message in second maze
     0there is a message scrawled in the dust in a flowery script, reading:
     0"this is not the maze where the pirate leaves his treasure chest."
    37*volcano and/or geyser
     0>$<
    38*vending machine
     0there is a massive vending machine here.  The instructions on it read:
     0"drop coins here to receive fresh batteries."
    39batteries
     0there are fresh batteries here.
   100some worn-out batteries have been discarded nearby.
    40*carpet and/or moss
     0>$<
    41rusty set of crampons
     0there is a rusty set of crampons here.
    50large gold nugget
     0there is a large sparkling nugget of gold here!
    51several diamonds
     0there are diamonds here!
    52bars of silver
     0there are bars of silver here!
    53precious jewelry
     0there is precious jewelry here!
    54rare coins
     0there are many coins here!
    55treasure chest
     0the pirate's treasure chest is here!
    56golden eggs
     0there is a large nest here, full of golden eggs!
   100the nest of golden eggs has vanished!
   200done!
    57jeweled trident
     0there is a jewel-encrusted trident here!
    58ming vase
     0there is a delicate, precious, ming vase here!
   100the vase is now resting, delicately, on a velvet pillow.
   200the floor is littered with worthless shards of pottery.
   300the ming vase drops with a delicate crash.
    59egg-sized emerald
     0there is an emerald here the size of a plover's egg!
    60platinum pyramid
     0there is a platinum pyramid here, 8 inches on a side!
    61glistening pearl
     0off to one side lies a glistening pearl!
    62persian rug
     0there is a persian rug spread out on the floor!
   100the dragon is sprawled out on a persian rug!!
    63rare spices
     0there are rare spices here!
    64golden chain
     0there is a golden chain lying in a heap on the floor!
   100the bear is locked to the wall with a golden chain!
   200there is a golden chain locked to the wall!
    65iridium crucible
     0there is a crucible of pure iridium off to one side!
    66crystal mushroom
     0there is a glittering crystal mushroom on the floor!
    -1
     6
     1Somewhere nearby is colossal cave, where others have found fortunes in
     1treasure and gold, though it is rumored that some who enter are never
     1seen again.  Magic is said to work in the cave.  I will be your eyes
     1and hands.  Direct me with commands of 1 or 2 words.  I should warn
     1you that I look at only the first five letters of each word, so you'll
     1have to enter "northeast" as "NE" to distinguish it from "north".
     1(should you get stuck, type "HELP" for some general hints.  For infor-
     1mation on how to end your adventure, etc., type "INFO".)
     1                              - - -
     2A little dwarf with a big knife blocks your way.
     3A little dwarf just walked around a corner, saw you, threw a little
     3axe at you which missed, cursed, and ran away.
     4There is a threatening little dwarf in the room with you!
     5One sharp nasty knife is thrown at you!
     6None of them hit you!
     7One of them gets you!
     8A hollow voice says "PLUGH".
     9There is no way to go that direction.
    10I am unsure how you are facing.  Use compass points or nearby objects.
    11I don't know in from out here.  Use compass points or name something
    11in the general direction you want to go.
    12I don't know how to apply that word here.
    13I don't understand that!
    14I'm game.  Would you care to explain how?
    15Sorry, but I am not allowed to give more detail.  I will repeat the
    15long description of your location.
    16It is now pitch dark.  If you proceed you will likely fall into a pit.
    17If you prefer, simply type W rather than west.
    18Are you trying to catch the bird?
    19The bird is frightened right now and you cannot catch it no matter
    19what you try.  Perhaps you might try later.
    20Are you trying to somehow deal with the snake?
    21You can't kill the snake, or drive it away, or avoid it, or anything
    21like that.  There is a way to get by, but you don't have the necessary
    21resources right now.
    22Do you really want to quit now?
    23You fell into a pit and broke every bone in your body!
    24You are already carrying it!
    25You can't be serious!
    26The bird was unafraid when you entered, but as you approach it becomes
    26disturbed and you cannot catch it.
    27You can catch the bird, but you cannot carry it.
    28There is nothing here with a lock!
    29You aren't carrying it!
    30The little bird attacks the green snake, and in an astounding flurry
    30drives the snake away.
    31You have no keys!
    32It has no lock.
    33I don't know how to lock or unlock such a thing.
    34It was already locked.
    35the grate is now locked.
    36The grate is now unlocked.
    37It was already unlocked.
    38You have no source of light.
    39Your lamp is now on.
    40Your lamp is now off.
    41There is no way to get past the bear to unlock the chain, which is
    41probably just as well.
    42Nothing happens.
    43Where?
    44There is nothing here to attack.
    45The little bird is now dead.  Its body disappears.
    46Attacking the snake both doesn't work and is very dangerous.
    47You killed a little dwarf.
    48You attack a little dwarf, but he dodges out of the way.
    49With what?  Your bare hands?
    50Good try, but that is an old worn-out magic word.
    51I know of places, actions, and things.  Most of my vocabulary
    51describes places and is used to move you there.  To move, try words
    51like forest, building, downstream, enter, east, west, north, south,
    51up, or down.  I know about a few special objects, like a black rod
    51hidden in the cave.  These objects can be manipulated using some of
    51the action words that I know.  Usually you will need to give both the
    51object and action words (in either order), but sometimes I can infer
    51the object from the verb alone.  Some objects also imply verbs; in
    51particular, "inventory" implies "take inventory", which causes me to
    51give you a list of what you're carrying.  The objects have side
    51effects; for instance, the rod scares the bird.  Usually people having
    51trouble moving just need to try a few more words.  Usually people
    51trying unsuccessfully to manipulate an object are attempting something
    51beyond their (or my!) capabilities and should try a completely
    51different tack.  To speed the game you can sometimes move long
    51distances with a single word.  For example, "building" usually gets
    51You to the building from anywhere above ground except when lost in the
    51forest.  Also, note that cave passages turn a lot, and that leaving a
    51room to the north does not guarantee entering the next from the south.
    51Good luck!
    52It misses!
    53It gets you!
    54Ok
    55You can't unlock the keys.
    56You have crawled around in some little holes and wound up back in the
    56main passage.
    57I don't know where the cave is, but hereabouts no stream can run on
    57the surface for long.  I would try the stream.
    58I need more detailed instructions to do that.
    59I can only tell you what you see as you move about and manipulate
    59things.  I cannot tell you where remote things are.
    60I don't know that word.
    61What?
    62Are you trying to get into the cave?
    63The grate is very solid and has a hardened steel lock.  You cannot
    63enter without a key, and there are no keys nearby.  I would recommend
    63looking elsewhere for the keys.
    64The trees of the forest are large hardwood oak and maple, with an
    64occasional grove of pine or spruce.  There is quite a bit of under-
    64growth, largely birch and ash saplings plus nondescript bushes of
    64various sorts.  This time of year visibility is quite restricted by
    64all the leaves, but travel is quite easy if you detour around the
    64spruce and berry bushes.
    65Welcome to Adventure!!  would you like instructions?
    66Digging without a shovel is quite impractical.  Even with a shovel
    66progress is unlikely.
    67Blasting requires dynamite.
    68I'm as confused as you are.
    69Mist is a white vapor, usually water, seen from time to time in
    69caverns.  It can be found anywhere but is frequently a sign of a deep
    69pit leading down to water.
    70Your feet are now wet.
    71I think I just lost my appetite.
    72Thank you, it was delicious!
    73You have taken a drink from the stream.  The water tastes strongly of
    73minerals, but is not unpleasant.  It is extremely cold.
    74The bottle of water is now empty.
    75Rubbing the electric lamp is not particularly rewarding.  Anyway,
    75nothing exciting happens.
    76Peculiar.  nothing unexpected happens.
    77Your bottle is empty and the ground is wet.
    78You can't pour that.
    79Watch it!
    80Which way?
    81Oh dear, you seem to have gotten yourself killed.  I might be able to
    81help you out, but I've never really done this before.  Do you want me
    81to try to reincarnate you?
    82All right.  but don't blame me if something goes wr......
    82       0       0    --- poof!! ---
    82You are engulfed in a cloud of orange smoke.  Coughing and gasping,
    82You emerge from the smoke and find....
    83You clumsy oaf, you've done it again!  I don't know how long I can
    83keep this up.  Do you want me to try reincarnating you again?
    84Okay, now where did I put my orange smoke?....  >POOF!<
    84Everything disappears in a dense cloud of orange smoke.
    85Now you've really done it!  I'm out of orange smoke!  You don't expect
    85me to do a decent reincarnation without any orange smoke, do you?
    86Okay, if you're so smart, do it yourself!  I'm leaving!
    90>>> MESSAGES 81 THRU 90 ARE RESERVED FOR "OBITUARIES". <<<
    91Sorry, but I no longer seem to remember how it was you got here.
    92You can't carry anything more.  You'll have to drop something first.
    93You can't go through a locked steel grate!
    94I believe what you want is right here with you.
    95You don't fit through a two-inch slit!
    96I respectfully suggest you go across the bridge instead of jumping.
    97There is no way across the fissure.
    98You're not carrying anything.
    99You are currently holding the following:
   100It's not hungry (it's merely pinin' for the fjords).  besides, you
   100have no bird seed.
   101The snake has now devoured your bird.
   102There's nothing here it wants to eat (except perhaps you).
   103You fool, dwarves eat only coal!  Now you've made him *REALLY* mad!!
   104You have nothing in which to carry it.
   105Your bottle is already full.
   106There is nothing here with which to fill the bottle.
   107Your bottle is now full of water.
   108Your bottle is now full of oil.
   109You can't fill that.
   110Don't be ridiculous!
   111The door is extremely rusty and refuses to open.
   112The plant indignantly shakes the oil off its leaves and asks, "Water?"
   113The hinges are quite thoroughly rusted now and won't budge.
   114The oil has freed up the hinges so that the door will now move,
   114although it requires some effort.
   115The plant has exceptionally deep roots and cannot be pulled free.
   116The dwarves' knives vanish as they strike the walls of the cave.
   117Something you're carrying won't fit through the tunnel with you.
   117You'd best take inventory and drop something.
   118You can't fit this five-foot clam through that little passage!
   119You can't fit this five-foot oyster through that little passage!
   120I advise you to put down the clam before opening it.  >STRAIN!<
   121I advise you to put down the oyster before opening it.  >WRENCH!<
   122You don't have anything strong enough to open the clam.
   123You don't have anything strong enough to open the oyster.
   124A glistening pearl falls out of the clam and rolls away.  Goodness,
   124this must really be an oyster.  (I never was very good at identifying
   124bivalves.)  Whatever it is, it has now snapped shut again.
   125The oyster creaks open, revealing nothing but oyster inside.  It
   125promptly snaps shut again.
   126You have crawled around in some little holes and found your way
   126blocked by a recent cave-in.  You are now back in the main passage.
   127There are faint rustling noises from the darkness behind you.
   128Out from the shadows behind you pounces a bearded pirate!  "Har, har,"
   128he chortles, "I'll just take all this booty and hide it away with me
   128chest deep in the maze!"  He snatches your treasure and vanishes into
   128the gloom.
   129A sepulchral voice reverberating through the cave, says, "Cave closing
   129soon.  All adventurers exit immediately through main office."
   130A mysterious recorded voice groans into life and announces:
   130   "This exit is closed.  Please leave via main office."
   131Tt looks as though you're dead.  Well, seeing as how it's so close to
   131closing time anyway, I think we'll just call it a day.
   132The sepulchral voice entones, "The cave is now closed."  As the echoes
   132fade, there is a blinding flash of light (and a small puff of orange
   132smoke). . . .    As your eyes refocus, you look around and find...
   133There is a loud explosion, and a twenty-foot hole appears in the far
   133wall, burying the dwarves in the rubble.  You march through the hole
   133and find yourself in the main office, where a cheering band of
   133friendly elves carry the conquering adventurer off into the sunset.
   134There is a loud explosion, and a twenty-foot hole appears in the far
   134wall, burying the snakes in the rubble.  A river of molten lava pours
   134in through the hole, destroying everything in its path, including you!
   135There is a loud explosion, and you are suddenly splashed across the
   135walls of the room.
   136The resulting ruckus has awakened the dwarves.  There are now several
   136threatening little dwarves in the room with you!  Most of them throw
   136knives at you!  All of them get you!
   137Oh, leave the poor unhappy bird alone.
   138I daresay whatever you want is around here somewhere.
   139I don't know the word "STOP".  Use "QUIT" if you want to give up.
   140You can't get there from here.
   141You are being followed by a very large, tame bear.
   142To suspend your adventure such that you can continue later, say
   142"SUSPEND" (or "PAUSE" or "SAVE").  To re-start your game at a later
   142time, start up a new adventure and after I say "you are standing...",
   142You must say "RESTORE".  You can't say "restore" at any other time.
   142to see how well you're doing, say "SCORE".  To get full credit for a
   142treasure, you must have left it safely in the building, though you get
   142partial credit just for locating it.  You lose points for getting
   142killed, or for quitting, though the former costs you more.  There are
   142also points based on how much (if any) of the cave you've managed to
   142explore; in particular, there is a large bonus just for getting in (to
   142distinguish the beginners from the rest of the pack), and there are
   142other ways to determine whether you've been through some of the more
   142harrowing sections.  If you think you've found all the treasures, just
   142keep exploring for a while.  If nothing interesting happens, you
   142haven't found them all yet.  If something interesting *DOES* happen,
   142it means you're getting a bonus and have an opportunity to garner many
   142more points in the master's section.  I may occasionally offer hints
   142if you seem to be having trouble.  If I do, i'll warn you in advance
   142how much it will affect your score to accept the hints.  Finally, to
   142save paper, you may specify "BRIEF", which tells me never to repeat
   142the full description of a place unless you explicitly ask me to.
   143Do you indeed wish to quit now?
   144There is nothing here with which to fill the vase.
   145The sudden change in temperature has delicately shattered the vase.
   146It is beyond your power to do that.
   147I don't know how.
   148It is too far up for you to reach.
   149You killed a little dwarf.  The body vanishes in a cloud of greasy
   149black smoke.
   150The shell is very strong and is impervious to attack.
   151What's the matter, can't you read?  Now you'd best start over.
   152The axe bounces harmlessly off the dragon's thick scales.
   153The dragon looks rather nasty.  You'd best not try to get by.
   154The little bird attacks the green dragon, and in an astounding flurry
   154gets burnt to a cinder.  The ashes blow away.
   155On what?
   156Okay, from now on i'll only describe a place in full the first time
   156you come to it.  To get the full description, say "LOOK".
   157Trolls are close relatives with the rocks and have skin as tough as
   157that of a rhinoceros.  The troll fends off your blows effortlessly.
   158The troll deftly catches the axe, examines it carefully, and tosses it
   158back, declaring, "Good workmanship, but it's not valuable enough."
   159The troll catches your treasure and scurries away out of sight.
   160The troll refuses to let you cross.
   161There is no longer any way across the chasm.
   162Just as you reach the other side, the bridge buckles beneath the
   162weight of the bear, which was still following you around.  You
   162scrabble desperately for support, but as the bridge collapses you
   162stumble back and fall into the chasm.
   163The bear lumbers toward the troll, who lets out a startled shriek and
   163scurries away.  The bear soon gives up the pursuit and wanders back.
   164The axe misses and lands near the bear where you can't get at it.
   165With what?  Your bare hands?  against *HIS* bear hands??
   166The bear is confused; he only wants to be your friend.
   167For crying out loud, the poor thing is already dead!
   168The bear eagerly wolfs down your food, after which he seems to calm
   168down considerably and even becomes rather friendly.
   169The bear is still chained to the wall.
   170The chain is still locked.
   171The chain is now unlocked.
   172The chain is now locked.
   173There is nothing here to which the chain can be locked.
   174There is nothing here to eat.
   175Do you want the hint?
   176Do you need help getting out of the maze?
   177You can make the passages look less alike by dropping things.
   178Are you trying to explore beyond the plover room?
   179There is a way to explore that region without having to worry about
   179falling into a pit.  None of the objects available is immediately
   179useful in discovering the secret.
   180Do you need help getting out of here?
   181Don't go west.
   182Gluttony is not one of the trolls vices. Avarice is, however.
   183Your lamp is getting dim.  You'd best start wrapping this up, unless
   183you can find some fresh batteries.  I seem to recall there's a vending
   183machine in the maze.  Bring some coins with you.
   184Your lamp has run out of power.
   185There's not much point in wandering around out here, and you can't
   185explore the cave without a lamp.  So let's just call it a day.
   186There are faint rustling noises from the darkness behind you.  As you
   186turn toward them, the beam of your lamp falls across a bearded pirate.
   186He is carrying a large chest.  "Shiver me timbers!" he cries, "I've
   186been spotted!  I'd best hie meself off to the maze to hide me chest!"
   186with that, he vanishes into the gloom.
   187Your lamp is getting dim.  You'd best go back for those batteries.
   188Your lamp is getting dim.  I'm taking the liberty of replacing the
   188batteries.
   189Your lamp is getting dim, and you're out of spare batteries.  You'd
   189best start wrapping this up.
   190I'm afraid the magazine is written in dwarvish.
   191"This is not the maze where the pirate leaves his treasure chest."
   192HMMM, this looks like a clue, which means it'll cost you 10 points to
   192read it.  Should I go ahead and read it anyway?
   193It says, "There is something strange about this place, such that one
   193of the words I've always known now has a new effect."
   194It says the same thing it did before.
   195I'm afraid I don't understand.
   196"Congratulations on bringing light into the dark-room!"
   197You strike the mirror a resounding blow, whereupon it shatters into a
   197myriad tiny fragments.
   198You have taken the vase and hurled it delicately to the ground.
   199You prod the nearest dwarf, who wakes up grumpily, takes one look at
   199you, curses, and grabs for his axe.
   200Is this acceptable?
   201There's no point in suspending a demonstration game.
   202The side room is so full of debris you can not enter.
   203The ice face is too slippery to climb with out the proper equipment.
   204There is no way to climb the dome.
   205The stream flows out through a pair of 1 foot diameter sewer pipes.
   205It would be advisable to use the exit.
    -1
     7
     1       3
     2       3
     3       8       9
     4      10
     5      11
     6       0
     7      14      15
     8      13
     9      94      -1
    10      96
    11      19      -1
    12      17      27
    13     101      -1
    14     103
    15       0
    16     106
    17       0      -1
    18       0
    19       3
    20       3
    21       0
    22       0
    23     109      -1
    24      25      -1
    25      23      67
    26     111      -1
    27      35     110
    28       0
    29      97      -1
    30       0      -1
    31     119     121
    32     117     122
    33     117     122
    34       0       0
    35     130      -1
    36       0      -1
    37     126      -1
    38     140      -1
    39       0
    40      96      -1
    41      16
    50      18
    51      27
    52     147
    53      29
    54      30
    55       0
    56      92
    57      95
    58      97
    59     100
    60     144
    61       0
    62     119     121
    63     127
    64     130      -1
    65     149
    66     150
    -1
     8
     1      24
     2      29
     3       0
     4      33
     5       0
     6      33
     7      38
     8      38
     9      42
    10      14
    11      43
    12     110
    13      29
    14     110
    15      73
    16      75
    17      29
    18      13
    19      59
    20      59
    21     174
    22     109
    23      67
    24      13
    25     147
    26     155
    27     195
    28     146
    29     110
    30      13
    31      13
    -1
     9
     0       1       2       3       4       5       6       7       8       9
     0      22      79     100     115     116     126     150
     2       1       3       4       7      38      95     113      24
     1      24
     3      46      47      48      54      56      58      82      85      86
     3     122     123     124     125     126     127     128     129     130
     4       8
     5      13
     6      19
     7      42      43      44      45      46      47      48      49      50
     7      52      53      54      55      56      80      81      82      86
     8      99     100     101
     9     108
    -1
    10
    35You are obviously a rank amateur.  Better luck next time.
   100Your score qualifies you as a novice class adventurer.
   130You have achieved the rating: "Experienced Adventurer".
   200You may now consider yourself a "Seasoned Adventurer".
   250You have reached "Junior Master" status.
   300Your score puts you in master adventurer class C.
   330Your score puts you in master adventurer class B.
   349Your score puts you in master adventurer class A.
   365You have achieved junior grandmaster status, congratulations!
  9999All of adventuredom gives tribute to you, adventurer grandmaster!
    -1
    11
     2    9999      10       0       0
     3    9999       5       0       0
     4       4       2      62      63
     5       5       2      18      19
     6       8       2      20      21
     7      75       4     176     177
     8      25       5     178     179
     9      20       3     180     181
    -1
    12
     1A large cloud of green smoke appears in front of you.  It clears away
     1to reveal a tall wizard, clothed in grey.  He fixes you with a steely
     1glare and declares, "This adventure has lasted too long."  With that
     1he makes a single pass over you with his hands, and everything around
     1you fades away into a grey nothingness.
     2Even wizards have to wait longer than that!
     3I'm terribly sorry, but colossal cave is closed.  Our hours are:
     4Only wizards are permitted within the cave right now.
     5We do allow visitors to make short explorations during our off hours.
     5Would you like to do that?
     6Colossal cave is open to regular adventurers at the following hours:
     7Very well.
     8Only a wizard may continue an adventure this soon.
     9I suggest you resume your adventure at a later time.
    10Do you wish to see the hours?
    11Do you wish to change the hours?
    12New magic word (null to leave unchanged):
    13New magic number (null to leave unchanged):
    14Do you wish to change the message of the day?
    15The new version has been saved, thank you...
    16Are you a wizard?
    17Prove it!  Say the magic word!
    18That is not what I thought it was.  Do you know what I thought it was?
    19Oh dear, you really *ARE* a wizard!  Sorry to have bothered you . . .
    20Foo, you are nothing but a charlatan!
    21New hours specified by defining "PRIME TIME".  Give only the hour
    21(e.g. 14, not 14:00 or 2pm).  Enter a negative number after last pair.
    22New hours for colossal cave:
    23Enter message limiting lines to 70 characters.  Terminate
    23the message with a line containing a single period (.) as its
    23first and only character.
    24Line too long, retype:
    25Not enough room for another line.  Ending message here.
    26Do you wish to (re)schedule the next holiday?
    27To begin how many days from today?
    28To last how many days (zero if no holiday)?
    29To be called what (up to 20 characters)?
    30Too small!  Assuming minimum value (45 minutes).
    31Break out of this and save your core-image.
    32 Be sure to save your core image.....
    -1
     0
